services:
  frontend:
    container_name: portfolio-frontend
    build:
      context: ./frontend
      dockerfile: Frontend.Dockerfile
    image: portfolio-frontend:1.3
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    container_name: portfolio-backend
    build:
      context: ./backend
      dockerfile: Backend.Dockerfile
    image: portfolio-backend:1.0
    ports:
      - "4000:4000"
    environment:
      - PG_DB=portfolio
      - PG_USER=artwojciech
      - PG_PASSWORD=postgres
      - PG_HOST=db
      - PORT=4000
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
    depends_on:
      - db

  db:
    container_name: portfolio-db
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: portfolio
      POSTGRES_USER: artwojciech
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

volumes:
  postgres_data: