version: "3.8"

services:
  backend:
    container_name: portfolio-backend
    build: .
    image: photography-portfolio
    ports:
      - "3000:3000"
    environment:
      - PG_DB=portfolio
      - PG_USER=artwojciech
      - PG_PASSWORD=postgres
      - PG_HOST=db
      - PORT=3000
    volumes:     ##tutaj musze sie zastanowic czy dobrze to zrobilem
      - .:/app
      - ./uploads:/app/uploads
    depends_on:
      - db

  db:
    container_name: portfolio-db
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: portfolio
      POSTGRES_USER: artwojciech
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always  #nie jestem pewny czy dalem to w dobrym miejscu

volumes:
  postgres_data:
